### ISSUE TITLE
Not Working On Live Server

### ISSUE THREAD

**Issue by chaimh770** [coderello/laravel-passport-social-grant#19]
This package was exactly what i needed, i implemented it and used it on my local server and all worked, but when i uploaded it to my live server i just get errors like this one "Client error: `POST https://mysite.com/oauth/token` resulted in a `400 Bad Request` response:
{"error":"unsupported_grant_type","error_description":"The authorization grant type is not supported by the authorizatio (truncated...)"

**Comment by karthikrajan-t2s** [comment]
Same error has been occured.

**Comment by cary67** [comment]
This error can also be caused by posting form-data to /oauth/token instead of raw JSON.  Form data will be ignored, returning an empty array to $requestParameters = (array) $request->getParsedBody(); in the AbstractGrant.php section of the oauth2-server used by Passport.  The grant_type field is undefined as a result and you get dumped to the default 'unsupported_grant_type' error.

**Comment by hivokas** [comment]
@chaimh770 @karthikrajan-t2s, please follow @cary67's advice.
